<!-- Static navbar -->
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle"
            data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#" data-toggle="modal"
            data-target="#acercade"><?php echo $this->config["sist_nom"] ?></a>
        </div>

        <div class="navbar-collapse collapse"></div><!--/.nav-collapse -->
    </div><!--/.container-fluid -->
</div>
